<!--
  README.md — Developer Profile for Yousef alshwawra
  Instructions:
  - Save this file as README.md in your GitHub profile repo (username/username).
  - If you want an animated greeting GIF, create/upload a small GIF to your repo (e.g., /assets/greeting.gif)
    and replace the IMAGE URL in the Hero section below.
  - To show improved GitHub data (contributions calendar, private repo data), consider using a backend or GitHub Actions.
-->

# Hi, I'm Yousef alshawra 👋
> Software Engineer — Backend & Frontend

<p align="center">
  <!-- Replace the GIF link below with your own greeting animation (optional) -->
  <img src="https://raw.githubusercontent.com/Youssef-Alshwawra/Youssef-Alshwawra/main/assets/greeting.gif" alt="Typing greeting" width="680" style="max-width:100%; border-radius:12px; box-shadow: 0 8px 30px rgba(2,6,23,0.6);" />
</p>

---

## 📫 Connect
[![Gmail Badge](https://img.shields.io/badge/-yousef.alshwawra@gmail.com-c14438?style=flat-square&logo=gmail&logoColor=white&link=mailto:yousef.alshwawra@gmail.com)](mailto:yousef.alshwawra@gmail.com)
[![GitHub](https://img.shields.io/badge/-@Youssef--Alshwawra-181717?style=flat-square&logo=github)](https://github.com/Youssef-Alshwawra)
[![LinkedIn](https://img.shields.io/badge/-Yousef-blue?style=flat-square&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/yousef-alshwawra/)
[![Instagram](https://img.shields.io/badge/-@leq1nd_youssef-E1306C?style=flat-square&logo=instagram&logoColor=white)](https://www.instagram.com/leq1nd_youssef/)

---

## 🛠️ Tech Stack

### Backend
<p>
  <img alt="Node.js" src="https://cdn.simpleicons.org/node.js" width="28" /> &nbsp;
  <img alt="Express" src="https://cdn.simpleicons.org/express" width="28" /> &nbsp;
  <img alt="Mongoose" src="https://cdn.simpleicons.org/mongodb" width="28" /> &nbsp;
  <img alt="Drizzle" src="https://cdn.simpleicons.org/drizzle-orm" width="28" /> &nbsp;
  <img alt="Sequelize" src="https://cdn.simpleicons.org/sequelize" width="28" /> &nbsp;
  <img alt=".NET" src="https://cdn.simpleicons.org/dotnet" width="28" /> &nbsp;
  <img alt="REST" src="https://cdn.simpleicons.org/rest" width="28" /> &nbsp;
  <span style="margin-left:8px">node.js • express.js • mongoose • drizzle • sequelize • .NET 8 • REST APIs • MVC</span>
</p>

### Frontend
<p>
  <img alt="React" src="https://cdn.simpleicons.org/react" width="28" /> &nbsp;
  <img alt="HTML5" src="https://cdn.simpleicons.org/html5" width="28" /> &nbsp;
  <img alt="CSS3" src="https://cdn.simpleicons.org/css3" width="28" /> &nbsp;
  <img alt="Tailwind" src="https://cdn.simpleicons.org/tailwindcss" width="28" /> &nbsp;
  <img alt="Bootstrap" src="https://cdn.simpleicons.org/bootstrap" width="28" /> &nbsp;
  <img alt="Next.js" src="https://cdn.simpleicons.org/next.js" width="28" /> &nbsp;
  <span style="margin-left:8px">React • HTML/CSS • TailwindCSS • Bootstrap • Next.js</span>
</p>

### Tools & Platforms
<p>
  <img alt="VSCode" src="https://cdn.simpleicons.org/visualstudiocode" width="28" /> &nbsp;
  <img alt="Cursor" src="https://cdn.simpleicons.org/cursor" width="28" /> &nbsp;
  <img alt="Docker" src="https://cdn.simpleicons.org/docker" width="28" /> &nbsp;
  <span style="margin-left:8px">VSCode • Cursor • Docker</span>
</p>

### Databases
<p>
  <img alt="Postgres" src="https://cdn.simpleicons.org/postgresql" width="28" /> &nbsp;
  <img alt="MongoDB" src="https://cdn.simpleicons.org/mongodb" width="28" /> &nbsp;
  <img alt="MySQL" src="https://cdn.simpleicons.org/mysql" width="28" /> &nbsp;
  <span style="margin-left:8px">PostgreSQL • MongoDB • MySQL</span>
</p>

---

## 📊 GitHub Stats

<!-- Replace `Youssef-Alshwawra` with your username if needed -->
<p align="center">
  <img alt="GitHub Stats" src="https://github-readme-stats.vercel.app/api?username=Youssef-Alshwawra&show_icons=true&hide_title=true&count_private=true" width="420" style="max-width:100%; border-radius:10px;" />
  &nbsp;
  <img alt="Top Languages" src="https://github-readme-stats.vercel.app/api/top-langs/?username=Youssef-Alshwawra&layout=compact&hide_title=true" width="300" style="max-width:100%; border-radius:10px;" />
</p>

<p align="center">
  <img alt="GitHub Streak" src="https://github-readme-streak-stats.herokuapp.com/?user=Youssef-Alshwawra&hide_border=true" width="640" style="max-width:100%; border-radius:10px;" />
</p>

> ⚠️ Note: The `github-readme-stats` and `github-readme-streak-stats` images are generated by external services. For complete control, you can self-host or replace with local images.

---

## 🔢 Top Languages (computed from public repos)
> Uses the GitHub public API to approximate primary languages across repos.

- **Top languages** are shown above in the `Top Languages` card.  
- If you want the language percentages to be hyper-accurate (by bytes), consider using a server-side script with the GitHub GraphQL API or a GitHub Action to precompute and embed the results.

---

## 💬 Developer Quote
> “Programs must be written for people to read, and only incidentally for machines to execute.” — Harold Abelson

*(Change or rotate quotes manually, or create a small GitHub Action that updates this README daily if you want automatic rotation.)*

---

## 🎯 Optional Enhancements / How to customize
- **Animated greeting**: Create or record a short typing GIF (size ~600×120) and place it at `/assets/greeting.gif`; update the image URL at the top.
- **Local icons**: Replace `cdn.simpleicons.org` URLs with `/icons/{name}.svg` if you want local SVG files.
- **Rotate quotes automatically**: Use a GitHub Action which edits README.md daily to pick a new quote from a list.
- **Contribution calendar / streak**: For contribution calendar embedding, you can use a third-party service or build a small server that queries the GraphQL API and renders an SVG.

---

## 🧾 Quick copy/paste snippets

**Mail:**  
`[Email Me](mailto:yousef.alshwawra@gmail.com)`

**GitHub Stats image (copy):**  
`![GitHub Stats](https://github-readme-stats.vercel.app/api?username=Youssef-Alshwawra&show_icons=true)`

**Top languages (copy):**  
`![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Youssef-Alshwawra)`

---

## 📌 Final notes
- This README is ready for immediate use. Paste it into `README.md` in your profile repository (`Youssef-Alshwawra/Youssef-Alshwawra`) and push.
- If you want, I can:
  - produce a **compact README** (for a cleaner GitHub profile look),
  - generate the **animated GIF** for the heading,
  - or create a **GitHub Action** workflow that rotates the quote daily and updates the README automatically.

Would you like the rotating-quote GitHub Action YAML next or a compact version of this README?
